#!/bin/bash
set -x
# File preview handler for lf.

set -C -f
IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}"


# Note that the cache file name is a function of file information, meaning if
# an image appears in multiple places across the machine, it will not have to
# be regenerated once seen.

case "$(file --dereference --brief --mime-type -- "$1")" in
	text/html) lynx -width="$4" -display_charset=utf-8 -dump "$1" ;;
	text/troff) man ./ "$1" | col -b ;;
	text/* | */xml | application/json) batcat --terminal-width "$(($4-2))" -f "$1" ;;
	application/*zip) atool --list -- "$1" ;;
	audio/* | application/octet-stream) mediainfo "$1" || exit 1 ;;
	application/pgp-encrypted) gpg -d -- "$1" ;;
esac
exit 1
