#
#    _______| |__  _ __ ___
#   |_  / __| '_ \| '__/ __|
#  _ / /\__ \ | | | | | (__
# (_)___|___/_| |_|_|  \___|
#

# Assure zsh we can display 256 colours
export TERM="ansi"
export EDITOR=nvim

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/.local/bin:$HOME/bin:$HOME/scripts/:$PATH

#
# Completion
#
autoload -U compinit && compinit -u
zmodload zsh/complist

zstyle ':completion:*' menu select
zstyle ':completion:*' completer _complete

# Make completion:
# - Case-insensitive.
# - Accept abbreviations after . or _ or - (ie. f.b -> foo.bar).
# - Substring complete (ie. bar -> foobar).
zstyle ':completion:*' matcher-list '' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' '+l:|=* r:|=*'

# Colorize completions using default `ls` colors.
zstyle ':completion:*' list-colors ''

# set VI to default editor
set -o vi

# History in cache directory:
HISTSIZE=10000
SAVEHIST=10000
HIST_STAMPS="dd.mm.yyyy"

export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.zsh_history
eval "$(starship init zsh)"

# Bindings
bindkey -s '^o' 'lf\n'
bindkey -s '^n' 'nvim\n'
bindkey -s '^p' 'pre-commit run -av\n'

source ~/.alias

# zsh-autosuggestions config
# https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#4f4f4f'
bindkey '^ ' autosuggest-accept # STRG-Space to complete

# tea completion
PROG=tea _CLI_ZSH_AUTOCOMPLETE_HACK=1 [ -f "/home/murdoc/.config/tea/autocomplete.zsh" ] && source "/home/murdoc/.config/tea/autocomplete.zsh"
# Arch
[ -f /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh ] && \
   source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
# Debian
[ -f /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh ] && \
   source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
# macOS
[ -f /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh ] && \
   source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh


# Load zsh-syntax-highlighting; should be last.
# Arch
[ -f /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ] && \
   source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# Debian
[ -f /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ] && \
   source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# macOS
[ -f /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ] && \
   source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

zstyle ':completion:*' rehash true

tmux a || tmux -f "${XDG_CONFIG_HOME:-$HOME/.config}"/tmux/tmux.conf
# tmux a || tmux -f "${XDG_CONFIG_HOME:-$HOME/.config}"/tmux/tmux.conf
